"""empty message

Revision ID: 4eefdb1159a5
Revises: 8ebaa4244f5d
Create Date: 2021-03-08 22:02:40.971629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eefdb1159a5'
down_revision = '8ebaa4244f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('input_item_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'input_item_name')
    # ### end Alembic commands ###
